contact_links:
  - name: Discussions
    url: https://github.com/graphistry/cu-cat/discussions
    about: Ask questions and discuss with other members of the community
  - name: Blank issue
    url: https://github.com/graphistry/cu-cat/issues/new
    about: Please note that Github Discussions should be used in most cases instead
